### creates Jane
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "j@j.com"
}

### creates John
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "j@j.com"
}

### creates jane's account
POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id":"0b3b962e-8742-40d7-bda5-55c4b36a95ff"
}
### creates john's account
POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id":"475efed7-6208-4938-abaf-8a417d936952"
}

### transaction from jane to john
POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_from":"cfa72612-9f48-4642-83f1-57c715f1eccb",
    "account_to":"468562bc-d96b-4087-8fb5-255a48f3655d",
    "amount": 1
}

### get balance for jane
GET http://localhost:8081/balances/cfa72612-9f48-4642-83f1-57c715f1eccb HTTP/1.1

### get balance for john
GET http://localhost:8081/balances/468562bc-d96b-4087-8fb5-255a48f3655d HTTP/1.1