POST http://localhost:3000/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "j@j.com"
}

### jane's account
POST http://localhost:3000/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id":"aeab6609-114f-4598-8812-3a84861e9671"
}
### john's account
POST http://localhost:3000/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id":"d357761d-4122-446e-8736-4d3ba7aa001e"
}

### transaction
POST http://localhost:3000/transactions HTTP/1.1
Content-Type: application/json

{
    "account_from":"b888990e-c392-48e9-8766-e754b1041a73",
    "account_to":"05f26ad8-f153-4851-b62d-bb79599b3d3e",
    "amount": 75
}
